version: '3.9'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    env_file: 
      - .env  
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app/app  
      - ./scripts:/app/scripts 
    command: ["fastapi", "run", "--workers", "4", "app/main.py"]
    restart: unless-stopped
